<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AetherXIV.Data\AetherXIV.Data.csproj" />
    <ProjectReference Include="..\AetherXIV.Server.Hosting\AetherXIV.Server.Hosting.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
