<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AetherXIV.Core.World</RootNamespace>
    <AssemblyName>AetherXIV.Core.World</AssemblyName>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);NU1701;SYSLIB0050;SYSLIB0051;SYSLIB0053</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AetherXIV.Core.Common\AetherXIV.Core.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cyotek.CircularBuffer" Version="1.0.0.0" />
    <PackageReference Include="MySql.Data" Version="8.0.31" />
    <PackageReference Include="NLog" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\..\Data\config\world_config.ini">
      <Link>world_config.ini</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
