<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AetherXIV.Core.Common\AetherXIV.Core.Common.csproj" />
    <ProjectReference Include="..\AetherXIV.Protocol\AetherXIV.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
